### ISSUE TITLE
What it takes to become someone like you ? 

### ISSUE THREAD

**Issue by KirankumarAmbati** [React-IND/React-India-2019-AMA-Kentcdodds#2]
I'm having huge passion for coding and want to teach people on various topics on JS n React(I ❤ React) but I am not sure how to get started and get going. I would love to hear from you on how you get the ball rolling. Thank you so much!

**Comment by kentcdodds** [comment]
- [Zero to 60 in Software Development: How to Jumpstart Your Career](https://www.youtube.com/watch?v=-qPh6I2hfjw&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf)
- [First question on my AMA: How did you get into programming?](https://github.com/kentcdodds/ama/issues/1)
- [How I am so productive](https://kentcdodds.com/blog/how-i-am-so-productive)
- [Intentional Career Building](https://kentcdodds.com/blog/intentional-career-building)
